FROM php:8.3.1-fpm-alpine

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

RUN mkdir -p /var/www/

WORKDIR /var/www/

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# MacOS staff group's gid is 20, so is the dialout group in alpine linux. We're not using it, let's just remove it.
RUN delgroup dialout

RUN apk --update add wget\
        php83 \
        php83-fpm \
        php83-opcache \
        php83-pecl-apcu \
        php83-mysqli \
        php83-pgsql \
        php83-json \
        php83-openssl \
        php83-curl \
        php83-zlib \
        php83-soap \
        php83-xml \
        php83-fileinfo \
        php83-phar \
        php83-intl \
        php83-dom \
        php83-xmlreader \
        php83-ctype \
        php83-session \
        php83-iconv \
        php83-tokenizer \
        php83-zip \
        php83-simplexml \
        php83-mbstring \
        php83-gd \
        autoconf \
        runit \
        curl \
        php83-pdo \
        php83-pdo_pgsql \
        postgresql-dev \
        libpq-dev \
        libzip-dev \
        libpng-dev \
        git \
        openssh-client
        # php8-pdo_mysql \
        # php8-pdo_sqlite \
        # php8-bz2 \

#docker deps
RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql pcntl intl zip exif gd bcmath
#redis installation
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && apk del pcre-dev ${PHPIZE_DEPS} \
  && rm -rf /tmp/pear

RUN apk add --update nodejs npm
RUN apk add --update npm

# Remove alpine cache
RUN rm -rf /var/cache/apk/*

CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
