version: "3.9"
services:
  db:
    image: 'postgres:15.5-bullseye'
    container_name: lesson-db
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - "5432:5432"
    volumes:
      - ./storage/docker/_db:/var/lib/postgresql/data'

  app:
    build:
      context: .
      dockerfile: docker/php/DockerFile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    container_name: lesson-app
    volumes:
      - ./:/var/www
      - ./docker/php/ex_php.ini:/usr/local/etc/php/conf.d/ex_php.ini
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: lesson-nginx
    ports:
      - "9000:9000"
      - "80:80"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/docker/logs/nginx:/var/log/nginx
    depends_on:
      - app
      - db
  redis:
    image: redis:alpine
    container_name: lesson-redis
    volumes:
      - ./storage/docker/redis:/data
    ports:
      - "6379:6379"
    depends_on:
      - app
      - db
      - nginx
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: lesson-mail
    ports:
      - '1025:1025'
      - '8025:8025'
