version: "3.9"
services:
  db:
    image: 'mysql:latest'
    container_name: lesson-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./storage/docker/_db:/var/lib/mysql'

  app:
    build:
      context: .
      dockerfile: docker/php/DockerFile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    container_name: lesson-app
    volumes:
      - ./:/var/www
      - ./docker/php/ex_php.ini:/usr/local/etc/php/conf.d/ex_php.ini
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: lesson-nginx
    ports:
      - "9000:9000"
      - "80:80"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/docker/logs/nginx:/var/log/nginx
    depends_on:
      - app
      - db
  redis:
    image: redis:alpine
    container_name: lesson-redis
    volumes:
      - ./storage/docker/redis:/data
    ports:
      - "6379:6379"
    depends_on:
      - app
      - db
      - nginx
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: lesson-mail
    ports:
      - '1025:1025'
      - '8025:8025'
