<?php

abstract class Vehicle
{
    const WHEELS = '4';

    abstract public function startEngine();

    abstract public function stopEngine();

    abstract public function wheelscount();

}

class car extends Vehicle
{
    public function startEngine()
    {
        echo "Машинка завелась: врум-врум-врум  " . "</br>";
    }

    public function stopEngine()
    {
        echo "Машинка заглохла: Брррррр " . "</br>";
    }

    public function wheelscount()
    {
        return parent::WHEELS . "</br>";// TODO: Change the autogenerated stub
    }
}

$car = new Car();
$car->startEngine();
$car->stopEngine();
echo "Колличество колес у данной техники: " . $car->wheelscount();


class bike extends Vehicle
{

    const WHEELS = '2';

    public function startEngine()
    {
        echo "Мотоцикл завелся: дыр-дыр-дыр " . "</br>";
    }

    public function stopEngine()
    {

        echo "Мотоцикл заглох: бы-бы-бы-бы" . "</br>";
    }

    public function wheelscount()
    {
        return self::WHEELS;
    }
}

$bike = new Bike();
$bike->startEngine();
$bike->stopEngine();
echo "Колличество колес у данной техники: " . $bike->wheelscount();














